ESTACIONES = {
    "Niquía": {"medio": "Metro", "transbordo": False},
    "Bello": {"medio": "Metro", "transbordo": False},
    "Madera": {"medio": "Metro", "transbordo": False},
    "Acevedo": {"medio": "Metro", "transbordo": True},
    "Tricentenario": {"medio": "Metro", "transbordo": False},
    "Caribe": {"medio": "Metro", "transbordo": False},
    "Universidad": {"medio": "Metro", "transbordo": False},
    "Hospital": {"medio": "Metro", "transbordo": True},
    "Prado": {"medio": "Metro", "transbordo": False},
    "Parque Berrío": {"medio": "Metro", "transbordo": False},
    "San Antonio": {"medio": "Metro", "transbordo": True},
    "San José": {"medio": "Tranvía", "transbordo": False},
    "Pabellón del Agua": {"medio": "Tranvía", "transbordo": False},
    "Bicentenario": {"medio": "Tranvía", "transbordo": False},
    "Buenos Aires": {"medio": "Tranvía", "transbordo": False},
    "Miraflores": {"medio": "Tranvía", "transbordo": True},
    "Loyola": {"medio": "Tranvía", "transbordo": False},
    "Alejandro Echavarría": {"medio": "Tranvía", "transbordo": False},
    "Oriente": {"medio": "Tranvía", "transbordo": True},
    "Andalucía": {"medio": "Metrocable", "transbordo": False},
    "Popular": {"medio": "Metrocable", "transbordo": False},
    "Santo Domingo": {"medio": "Metrocable", "transbordo": False},
    "Las Torres": {"medio": "Metrocable", "transbordo": False},
    "Villa Sierra": {"medio": "Metrocable", "transbordo": False},
    "Hospital 1": {"medio": "Metroplús", "transbordo": True},
    "Ruta N – U. de A": {"medio": "Metroplús", "transbordo": False},
    "Chagualo": {"medio": "Metroplús", "transbordo": False},
    "U. de M. 1": {"medio": "Metroplús", "transbordo": False},
}

CONEXIONES = [
    ("Niquía", "Bello", "Metro", 3, 800),
    ("Bello", "Madera", "Metro", 3, 800),
    ("Madera", "Acevedo", "Metro", 4, 800),
    ("Acevedo", "Tricentenario", "Metro", 3, 800),
    ("Tricentenario", "Caribe", "Metro", 3, 800),
    ("Caribe", "Universidad", "Metro", 3, 800),
    ("Universidad", "Hospital", "Metro", 3, 800),
    ("Hospital", "Prado", "Metro", 3, 800),
    ("Prado", "Parque Berrío", "Metro", 3, 800),
    ("Parque Berrío", "San Antonio", "Metro", 3, 800),
    ("San Antonio", "San José", "Tranvía", 3, 800),
    ("San José", "Pabellón del Agua", "Tranvía", 3, 800),
    ("Pabellón del Agua", "Bicentenario", "Tranvía", 3, 800),
    ("Bicentenario", "Buenos Aires", "Tranvía", 3, 800),
    ("Buenos Aires", "Miraflores", "Tranvía", 3, 800),
    ("Miraflores", "Loyola", "Tranvía", 3, 800),
    ("Loyola", "Alejandro Echavarría", "Tranvía", 3, 800),
    ("Alejandro Echavarría", "Oriente", "Tranvía", 4, 800),
    ("Acevedo", "Andalucía", "Metrocable", 3, 700),
    ("Andalucía", "Popular", "Metrocable", 3, 700),
    ("Popular", "Santo Domingo", "Metrocable", 4, 700),
    ("Oriente", "Las Torres", "Metrocable", 3, 700),
    ("Las Torres", "Villa Sierra", "Metrocable", 2, 700),
    ("Hospital 1", "Ruta N – U. de A", "Metroplús", 3, 600),
    ("Ruta N – U. de A", "Chagualo", "Metroplús", 3, 600),
    ("Chagualo", "U. de M. 1", "Metroplús", 8, 600),
    ("Hospital", "Hospital 1", "Transbordo", 2, 0),
    ("Acevedo", "Andalucía", "Transbordo", 2, 0),
    ("Oriente", "Las Torres", "Transbordo", 2, 0),
]

REGLAS = [
    "R1: una ruta de un solo tramo es directa.",
    "R2: menos transbordos favorece comodidad.",
    "R3: menor tiempo favorece rapidez.",
    "R4: menor costo favorece economía.",
    "R5: los cambios de medio deben ocurrir en puntos de transferencia.",
]
 